name: Pull Request CI

on:
  pull_request:
    branches:
      - dev  # dev로 PR 시 실행

jobs:
  build-test-push:
    name: Build, Test, and Push Docker Image to Harbor
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 레포지토리 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Docker 빌드 툴셋 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker 이미지를 빌드
      - name: Build Docker Image
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          echo $HARBOR_PASSWORD | docker login harbor.mycompany.com -u $HARBOR_USERNAME --password-stdin
          docker build -t harbor.mycompany.com/my-app/my-app:pr-${{ github.event.number }} .
          docker tag harbor.mycompany.com/my-app/my-app:pr-${{ github.event.number }} harbor.mycompany.com/my-app/my-app:latest

      # 4. Docker 이미지를 Harbor로 푸시
      - name: Push Docker Image to Harbor
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          docker push harbor.mycompany.com/my-app/my-app:pr-${{ github.event.number }}
          docker push harbor.mycompany.com/my-app/my-app:latest

      # 5. 테스트 실행
      - name: Run Unit Tests
        run: |
          npm install
          npm test

      # 6. Lint 검사
      - name: Run Linter
        run: |
          npm run lint
